# After how many seconds the round will end. [Default: 180]
total_time_in_seconds: 180
# A list of maps that can be used for this event.
available_maps:
- # The chance of getting this map.
  chance: 50
  # The map and information.
  map:
    # The name of the map schematic.
    map_name: 'Snowball'
    # The position to spawn the map.
    position:
      x: 0
      y: 0
      z: 30
    # The rotation of the map.
    rotation:
      x: 0
      y: 0
      z: 0
    # The scale of the map.
    scale:
      x: 1
      y: 1
      z: 1
    # Whether the object needs to be optimized.
    is_static: false
- # The chance of getting this map.
  chance: 50
  # The map and information.
  map:
    # The name of the map schematic.
    map_name: 'Dodgeball'
    # The position to spawn the map.
    position:
      x: 0
      y: 0
      z: 30
    # The rotation of the map.
    rotation:
      x: 0
      y: 0
      z: 0
    # The scale of the map.
    scale:
      x: 1
      y: 1
      z: 1
    # Whether the object needs to be optimized.
    is_static: false
# A list of sounds that can be used for this event.
available_sounds: []
# Some plugins may override this out of necessity.
enable_friendly_fire_autoban: Default
# Some plugins may override this out of necessity.
enable_friendly_fire: Default
# Should this plugin output debug logs.
debug: false
# DO NOT CHANGE THIS. IT WILL BREAK THINGS. AutoEvent will automatically manage this setting.
config_version: '1.0.0'
