# The delay between the selection of platforms that fall from 2 to 0.1. [Default: 1 - 0.3]
delay_in_seconds:
  # The value at the start of the game.
  starting_value: 1
  # The value at the end of the game.
  ending_value: 0.3
  # The method that the value will be calculated.
  calculation_method: Linear
# The delay between the color warning, and the platform falling from 3 to 0. [Default 0.7 - 0]
warning_delay_in_seconds:
  # The value at the start of the game.
  starting_value: 0.7
  # The value at the end of the game.
  ending_value: 0
  # The method that the value will be calculated.
  calculation_method: Linear
# Should platforms have a color warning for when they are about to fall.
platforms_have_color_warning: true
# A list of maps that can be used for this event.
available_maps:
- # The chance of getting this map.
  chance: 50
  # The map and information.
  map:
    # The name of the map schematic.
    map_name: 'FallDown'
    # The position to spawn the map.
    position:
      x: 10
      y: 1020
      z: -43.68
    # The rotation of the map.
    rotation:
      x: 0
      y: 0
      z: 0
    # The scale of the map.
    scale:
      x: 1
      y: 1
      z: 1
    # Whether the object needs to be optimized.
    is_static: false
- # The chance of getting this map.
  chance: 50
  # The map and information.
  map:
    # The name of the map schematic.
    map_name: 'FallDown_Xmas2024'
    # The position to spawn the map.
    position:
      x: 10
      y: 1020
      z: -43.68
    # The rotation of the map.
    rotation:
      x: 0
      y: 0
      z: 0
    # The scale of the map.
    scale:
      x: 1
      y: 1
      z: 1
    # Whether the object needs to be optimized.
    is_static: false
# A list of sounds that can be used for this event.
available_sounds: []
# Some plugins may override this out of necessity.
enable_friendly_fire_autoban: Default
# Some plugins may override this out of necessity.
enable_friendly_fire: Default
# Should this plugin output debug logs.
debug: false
# DO NOT CHANGE THIS. IT WILL BREAK THINGS. AutoEvent will automatically manage this setting.
config_version: ""
