binary_values_for_console:
  A:
  - 0
  - 1
  - 2
  - 3
  - 6
  - 7
  - 8
  - 9
  B:
  - 0
  - 1
  - 3
  - 4
  - 5
  - 7
  - 9
  - 14
  - 15
  C:
  - 0
  - 1
  - 4
  - 5
  - 6
  - 8
  D:
  - 0
  - 1
  - 4
  - 5
  - 7
  - 9
  - 14
  - 15
  E:
  - 0
  - 1
  - 2
  - 3
  - 4
  - 5
  - 6
  - 8
  F:
  - 0
  - 1
  - 2
  - 3
  - 6
  - 8
  G:
  - 0
  - 1
  - 3
  - 4
  - 5
  - 6
  - 8
  - 9
  H:
  - 2
  - 3
  - 6
  - 7
  - 8
  - 9
  I:
  - 0
  - 1
  - 4
  - 5
  - 14
  - 15
  J:
  - 4
  - 5
  - 7
  - 8
  - 9
  K:
  - 2
  - 6
  - 8
  - 11
  - 13
  L:
  - 4
  - 5
  - 6
  - 8
  M:
  - 6
  - 7
  - 8
  - 9
  - 10
  - 11
  N:
  - 6
  - 7
  - 8
  - 9
  - 10
  - 13
  O:
  - 0
  - 1
  - 4
  - 5
  - 6
  - 7
  - 8
  - 9
  P:
  - 0
  - 1
  - 2
  - 3
  - 6
  - 7
  - 8
  Q:
  - 0
  - 1
  - 4
  - 5
  - 6
  - 7
  - 8
  - 9
  - 13
  R:
  - 0
  - 1
  - 2
  - 3
  - 6
  - 7
  - 8
  - 13
  S:
  - 0
  - 1
  - 2
  - 3
  - 4
  - 5
  - 6
  - 9
  T:
  - 0
  - 1
  - 14
  - 15
  U:
  - 4
  - 5
  - 6
  - 7
  - 8
  - 9
  V:
  - 6
  - 8
  - 11
  - 12
  W:
  - 6
  - 7
  - 8
  - 9
  - 12
  - 13
  X:
  - 10
  - 11
  - 12
  - 13
  Y:
  - 2
  - 3
  - 6
  - 7
  - 15
  Z:
  - 0
  - 1
  - 4
  - 5
  - 11
  - 12
  0:
  - 0
  - 1
  - 4
  - 5
  - 6
  - 7
  - 8
  - 9
  - 10
  - 11
  - 12
  - 13
  1:
  - 7
  - 9
  - 11
  2:
  - 0
  - 1
  - 2
  - 3
  - 4
  - 5
  - 7
  - 8
  3:
  - 0
  - 1
  - 3
  - 4
  - 5
  - 7
  - 9
  4:
  - 2
  - 3
  - 6
  - 7
  - 9
  5:
  - 0
  - 1
  - 2
  - 3
  - 4
  - 5
  - 6
  - 9
  - 10
  - 13
  6:
  - 0
  - 2
  - 3
  - 4
  - 5
  - 6
  - 8
  - 9
  7:
  - 0
  - 1
  - 7
  - 9
  8:
  - 0
  - 1
  - 2
  - 3
  - 4
  - 5
  - 6
  - 7
  - 8
  - 9
  9:
  - 0
  - 1
  - 2
  - 3
  - 5
  - 6
  - 7
  - 9
  ' ': []
  ',':
  - 12
  "'":
  - 11
  '-':
  - 2
  - 3
  +:
  - 2
  - 3
  - 14
  - 15
  '?':
  - 0
  - 2
  - 14
  - 16
  '[':
  - 0
  - 4
  - 6
  - 8
  ']':
  - 1
  - 5
  - 7
  - 9
  /:
  - 11
  - 12
  '/':
  - 10
  - 13
  _:
  - 4
  - 5
  <:
  - 11
  - 13
  '>':
  - 10
  - 12
  $:
  - 0
  - 1
  - 2
  - 3
  - 4
  - 5
  - 6
  - 8
  - 14
  - 15
  '@':
  - 0
  - 1
  - 3
  - 4
  - 5
  - 6
  - 7
  - 8
  - 14
  '&':
  - 0
  - 1
  - 4
  - 5
  - 9
  - 10
  - 11
  - 12
  - 13
  .:
  - 16
  '!':
  - 6
  - 16
count_tracker_targets:
  D:
  - ClassD
  G:
  - FacilityGuard
  S:
  - Scientist
  M:
  - NtfCaptain
  - NtfPrivate
  - NtfSergeant
  - NtfSpecialist
  O:
  - Scp049
  - Scp096
  - Scp106
  - Scp173
  - Scp939
  - ChaosConscript
  - ChaosMarauder
  - ChaosRepressor
  - ChaosRifleman
elevator_settings:
  Main Elevator:
    animation_names:
    - 'LiftDoorOpen'
    - 'LiftDoorClose'
    door_waiting_time: 3
    door_animation_cool_time: 1.20000005
    disallowed_floors: []
    elevator_speed: 2
  Storage Elevator:
    animation_names:
    - 'StorageLiftDoorAnimation'
    - 'StorageDoorClose'
    door_waiting_time: 3
    door_animation_cool_time: 1.20000005
    disallowed_floors: []
    elevator_speed: 2
respawn_effect_names:
  ChaosCar: ChaosEntering
  Helicopter: Landing
respawn_team_names:
  ChaosCar: ChaosInsurgency
  Helicopter: NineTailedFox
counter_activating_lines:
- - 0
  - 2
  - 3
  - 4
  - 5
  - 6
- - 5
  - 6
- - 0
  - 1
  - 2
  - 3
  - 5
- - 0
  - 1
  - 2
  - 5
  - 6
- - 1
  - 4
  - 5
  - 6
- - 0
  - 1
  - 2
  - 4
  - 6
- - 0
  - 1
  - 2
  - 3
  - 4
  - 6
- - 0
  - 5
  - 6
- - 0
  - 1
  - 2
  - 3
  - 4
  - 5
  - 6
- - 0
  - 1
  - 2
  - 4
  - 5
  - 6
use_experimental_stuff: false
