# Whether the default player spawnpoints should be removed. Keep in mind, that given role spawnpoint will be removed only if there is at least one custom spawn point of that type.
remove_default_spawn_points: false
# List of possible names for ragdolls spawned by RagdollSpawnPoints.
ragdoll_role_names:
  ClassD:
  - 'D-9341'
vanilla_doors: {}
vanilla_tesla_properties:
  ignored_roles: []
  ignored_items: []
  inventory_item: true
  damage_multiplier: 1
doors:
- door_type: HeavyContainmentDoor
  is_open: false
  is_locked: false
  keycard_permissions: ContainmentLevelOne
  ignored_damage_sources: Weapon
  door_health: 150
  lock_on_event: None
  position:
    x: -5.328484
    y: 0
    z: -1.388123
  rotation:
    x: 0
    y: 0
    z: 0
  scale:
    x: 1
    y: 1
    z: 1
  room_type: Hcz939
- door_type: LightContainmentDoor
  is_open: false
  is_locked: true
  keycard_permissions: None
  ignored_damage_sources: Weapon
  door_health: 9999
  lock_on_event: None
  position:
    x: -1.5
    y: 0
    z: 2.384186E-07
  rotation:
    x: 0
    y: -270
    z: 0
  scale:
    x: 1
    y: 1
    z: 1
  room_type: LczArmory
- door_type: EntranceDoor
  is_open: false
  is_locked: false
  keycard_permissions: ContainmentLevelOne
  ignored_damage_sources: Weapon
  door_health: 150
  lock_on_event: None
  position:
    x: 30.29447
    y: 970.282
    z: -58.63335
  rotation:
    x: 0
    y: 0
    z: 0
  scale:
    x: 1
    y: 1
    z: 1
  room_type: Surface
- door_type: EntranceDoor
  is_open: false
  is_locked: false
  keycard_permissions: Intercom
  ignored_damage_sources: Weapon
  door_health: 150
  lock_on_event: None
  position:
    x: 40.54408
    y: 970.282
    z: -52.13514
  rotation:
    x: 0
    y: 0
    z: 0
  scale:
    x: 1
    y: 1
    z: 1
  room_type: Surface
- door_type: EntranceDoor
  is_open: false
  is_locked: false
  keycard_permissions: Intercom
  ignored_damage_sources: Weapon
  door_health: 150
  lock_on_event: None
  position:
    x: 36.59706
    y: 970.2805
    z: -33.92418
  rotation:
    x: 0
    y: 0
    z: 0
  scale:
    x: 1
    y: 1
    z: 1
  room_type: Surface
- door_type: EntranceDoor
  is_open: false
  is_locked: false
  keycard_permissions: ContainmentLevelOne
  ignored_damage_sources: Weapon
  door_health: 150
  lock_on_event: None
  position:
    x: 28.94334
    y: 970.282
    z: -33.85674
  rotation:
    x: 0
    y: 0
    z: 0
  scale:
    x: 1
    y: 1
    z: 1
  room_type: Surface
- door_type: EntranceDoor
  is_open: false
  is_locked: false
  keycard_permissions: ContainmentLevelOne
  ignored_damage_sources: Weapon
  door_health: 150
  lock_on_event: None
  position:
    x: 24.29576
    y: 953.3395
    z: -50.69939
  rotation:
    x: 0
    y: 90
    z: 0
  scale:
    x: 1
    y: 0.93
    z: 1
  room_type: Surface
- door_type: EntranceDoor
  is_open: false
  is_locked: false
  keycard_permissions: ContainmentLevelOne
  ignored_damage_sources: Weapon
  door_health: 150
  lock_on_event: None
  position:
    x: 9.735328
    y: 953.1732
    z: -50.68909
  rotation:
    x: 0
    y: 90
    z: 0
  scale:
    x: 1
    y: 1
    z: 1
  room_type: Surface
- door_type: EntranceDoor
  is_open: false
  is_locked: false
  keycard_permissions: ContainmentLevelOne
  ignored_damage_sources: Weapon
  door_health: 150
  lock_on_event: None
  position:
    x: 24.55149
    y: 950.1982
    z: -55.19765
  rotation:
    x: 0
    y: 90
    z: 0
  scale:
    x: 1
    y: 1
    z: 1
  room_type: Surface
- door_type: EntranceDoor
  is_open: false
  is_locked: false
  keycard_permissions: ContainmentLevelOne
  ignored_damage_sources: Weapon
  door_health: 150
  lock_on_event: None
  position:
    x: 24.57941
    y: 950.1982
    z: -41.86635
  rotation:
    x: 0
    y: 90
    z: 0
  scale:
    x: 1
    y: 1
    z: 1
  room_type: Surface
- door_type: HeavyContainmentDoor
  is_open: false
  is_locked: false
  keycard_permissions: ContainmentLevelOne
  ignored_damage_sources: Weapon
  door_health: 150
  lock_on_event: None
  position:
    x: 35.44845
    y: 950.1983
    z: -23.71634
  rotation:
    x: 0
    y: 0
    z: 0
  scale:
    x: 1
    y: 1
    z: 1
  room_type: Surface
work_stations:
- is_interactable: true
  position:
    x: 37.84
    y: 970.28
    z: -51.6
  rotation:
    x: 0
    y: 0
    z: 0
  scale:
    x: 1
    y: 1
    z: 1
  room_type: Surface
item_spawn_points: []
player_spawn_points:
- spawnable_team: ClassD
  position:
    x: 35.5402
    y: 951.4483
    z: -31.27753
  room_type: Surface
ragdoll_spawn_points: []
shooting_targets: []
primitives: []
light_sources:
- color: 'blue'
  intensity: 1
  range: 1
  shadows: false
  position:
    x: -1.620003
    y: 1.369995
    z: -4.099998
  room_type: HczHid
- color: 'blue'
  intensity: 1
  range: 1.10000002
  shadows: false
  position:
    x: -2.100006
    y: 3.03
    z: 2.384186E-07
  room_type: LczArmory
- color: 'white'
  intensity: 1
  range: 20
  shadows: false
  position:
    x: -4.730003
    y: 2.79
    z: 5.540001
  room_type: Lcz914
- color: 'white'
  intensity: 1
  range: 20
  shadows: false
  position:
    x: 18.34
    y: 952.99
    z: -64.33
  room_type: Surface
- color: 'white'
  intensity: 1
  range: 20
  shadows: false
  position:
    x: 26.10135
    y: 952.99
    z: -58.87881
  room_type: Surface
room_lights: []
teleports:
- target_teleporters:
  - id: 0
    chance: 100
  allowed_roles:
  - 'Scp0492'
  - 'Scp049'
  - 'Scp096'
  - 'Scp106'
  - 'Scp173'
  - 'Scp939'
  - 'Scp3114'
  - 'ZombieFlamingo'
  - 'ClassD'
  - 'Scientist'
  - 'FacilityGuard'
  - 'NtfPrivate'
  - 'NtfSergeant'
  - 'NtfSpecialist'
  - 'NtfCaptain'
  - 'ChaosConscript'
  - 'ChaosRifleman'
  - 'ChaosRepressor'
  - 'ChaosMarauder'
  - 'Tutorial'
  - 'AlphaFlamingo'
  - 'Flamingo'
  cooldown: 1
  teleport_flags: Player
  lock_on_event: None
  teleport_sound_id: -1
  player_rotation_x: 120
  player_rotation_y: 90
  room_type: Surface
  object_id: 1
  position:
    x: 35.39892
    y: 951.1983
    z: -22.04308
  rotation:
    x: 0
    y: 0
    z: 0
  scale:
    x: 1
    y: 1
    z: 1
- target_teleporters:
  - id: 1
    chance: 100
  allowed_roles:
  - 'Scp0492'
  - 'Scp049'
  - 'Scp096'
  - 'Scp106'
  - 'Scp173'
  - 'Scp939'
  - 'Scp3114'
  - 'ZombieFlamingo'
  - 'ClassD'
  - 'Scientist'
  - 'FacilityGuard'
  - 'NtfPrivate'
  - 'NtfSergeant'
  - 'NtfSpecialist'
  - 'NtfCaptain'
  - 'ChaosConscript'
  - 'ChaosRifleman'
  - 'ChaosRepressor'
  - 'ChaosMarauder'
  - 'Tutorial'
  - 'AlphaFlamingo'
  - 'Flamingo'
  cooldown: 1
  teleport_flags: Player
  lock_on_event: None
  teleport_sound_id: -1
  player_rotation_x: 90
  player_rotation_y: 90
  room_type: LczClassDSpawn
  object_id: 0
  position:
    x: -24.98083
    y: 1.0375
    z: 0.0004043579
  rotation:
    x: 0
    y: 0
    z: 0
  scale:
    x: 1
    y: 1
    z: 1
- target_teleporters:
  - id: 2
    chance: 100
  allowed_roles:
  - 'Scp0492'
  - 'Scp049'
  - 'Scp096'
  - 'Scp106'
  - 'Scp173'
  - 'Scp939'
  - 'Scp3114'
  - 'ZombieFlamingo'
  - 'ClassD'
  - 'Scientist'
  - 'FacilityGuard'
  - 'NtfPrivate'
  - 'NtfSergeant'
  - 'NtfSpecialist'
  - 'NtfCaptain'
  - 'ChaosConscript'
  - 'ChaosRifleman'
  - 'ChaosRepressor'
  - 'ChaosMarauder'
  - 'Tutorial'
  - 'AlphaFlamingo'
  - 'Flamingo'
  cooldown: 1
  teleport_flags: Player
  lock_on_event: None
  teleport_sound_id: -1
  player_rotation_x: 180
  player_rotation_y: 
  room_type: Surface
  object_id: 3
  position:
    x: 17.23956
    y: 971.282
    z: -16.36187
  rotation:
    x: 0
    y: 0
    z: 0
  scale:
    x: 1
    y: 1
    z: 1
- target_teleporters:
  - id: 3
    chance: 100
  allowed_roles:
  - 'Scp0492'
  - 'Scp049'
  - 'Scp096'
  - 'Scp106'
  - 'Scp173'
  - 'Scp939'
  - 'Scp3114'
  - 'ZombieFlamingo'
  - 'ClassD'
  - 'Scientist'
  - 'FacilityGuard'
  - 'NtfPrivate'
  - 'NtfSergeant'
  - 'NtfSpecialist'
  - 'NtfCaptain'
  - 'ChaosConscript'
  - 'ChaosRifleman'
  - 'ChaosRepressor'
  - 'ChaosMarauder'
  - 'Tutorial'
  - 'AlphaFlamingo'
  - 'Flamingo'
  cooldown: 1
  teleport_flags: Player
  lock_on_event: None
  teleport_sound_id: -1
  player_rotation_x: 270
  player_rotation_y: 180
  room_type: LczArmory
  object_id: 2
  position:
    x: -1.673722
    y: 0.9999995
    z: -0.02741218
  rotation:
    x: 0
    y: 0
    z: 0
  scale:
    x: 1
    y: 1
    z: 1
- target_teleporters:
  - id: 4
    chance: 100
  allowed_roles:
  - 'Scp0492'
  - 'Scp049'
  - 'Scp096'
  - 'Scp106'
  - 'Scp173'
  - 'Scp939'
  - 'Scp3114'
  - 'ZombieFlamingo'
  - 'ClassD'
  - 'Scientist'
  - 'FacilityGuard'
  - 'NtfPrivate'
  - 'NtfSergeant'
  - 'NtfSpecialist'
  - 'NtfCaptain'
  - 'ChaosConscript'
  - 'ChaosRifleman'
  - 'ChaosRepressor'
  - 'ChaosMarauder'
  - 'Tutorial'
  - 'AlphaFlamingo'
  - 'Flamingo'
  cooldown: 1
  teleport_flags: Player
  lock_on_event: None
  teleport_sound_id: -1
  player_rotation_x: 180
  player_rotation_y: 90
  room_type: Lcz173
  object_id: 5
  position:
    x: 1.855598
    y: 15.32478
    z: 3.223541
  rotation:
    x: 0
    y: 0
    z: 0
  scale:
    x: 1
    y: 1
    z: 1
- target_teleporters:
  - id: 5
    chance: 100
  allowed_roles:
  - 'Scp0492'
  - 'Scp049'
  - 'Scp096'
  - 'Scp106'
  - 'Scp173'
  - 'Scp939'
  - 'Scp3114'
  - 'ZombieFlamingo'
  - 'ClassD'
  - 'Scientist'
  - 'FacilityGuard'
  - 'NtfPrivate'
  - 'NtfSergeant'
  - 'NtfSpecialist'
  - 'NtfCaptain'
  - 'ChaosConscript'
  - 'ChaosRifleman'
  - 'ChaosRepressor'
  - 'ChaosMarauder'
  - 'Tutorial'
  - 'AlphaFlamingo'
  - 'Flamingo'
  cooldown: 1
  teleport_flags: Player
  lock_on_event: None
  teleport_sound_id: -1
  player_rotation_x: 90
  player_rotation_y: 90
  room_type: Lcz173
  object_id: 4
  position:
    x: 9.021576
    y: 12.46896
    z: -1.987198
  rotation:
    x: 0
    y: 0
    z: 0
  scale:
    x: 1
    y: 1
    z: 1
- target_teleporters:
  - id: 6
    chance: 100
  allowed_roles:
  - 'Scp0492'
  - 'Scp049'
  - 'Scp096'
  - 'Scp106'
  - 'Scp173'
  - 'Scp939'
  - 'Scp3114'
  - 'ZombieFlamingo'
  - 'ClassD'
  - 'Scientist'
  - 'FacilityGuard'
  - 'NtfPrivate'
  - 'NtfSergeant'
  - 'NtfSpecialist'
  - 'NtfCaptain'
  - 'ChaosConscript'
  - 'ChaosRifleman'
  - 'ChaosRepressor'
  - 'ChaosMarauder'
  - 'Tutorial'
  - 'AlphaFlamingo'
  - 'Flamingo'
  cooldown: 1
  teleport_flags: Player
  lock_on_event: None
  teleport_sound_id: -1
  player_rotation_x: 
  player_rotation_y: 
  room_type: Lcz914
  object_id: 7
  position:
    x: -6.400497
    y: 0.9999979
    z: 3.745041
  rotation:
    x: 0
    y: 0
    z: 0
  scale:
    x: 1
    y: 1
    z: 1
- target_teleporters:
  - id: 7
    chance: 100
  allowed_roles:
  - 'Scp0492'
  - 'Scp049'
  - 'Scp096'
  - 'Scp106'
  - 'Scp173'
  - 'Scp939'
  - 'Scp3114'
  - 'ZombieFlamingo'
  - 'ClassD'
  - 'Scientist'
  - 'FacilityGuard'
  - 'NtfPrivate'
  - 'NtfSergeant'
  - 'NtfSpecialist'
  - 'NtfCaptain'
  - 'ChaosConscript'
  - 'ChaosRifleman'
  - 'ChaosRepressor'
  - 'ChaosMarauder'
  - 'Tutorial'
  - 'AlphaFlamingo'
  - 'Flamingo'
  cooldown: 1
  teleport_flags: Player
  lock_on_event: None
  teleport_sound_id: -1
  player_rotation_x: 
  player_rotation_y: 
  room_type: Lcz914
  object_id: 6
  position:
    x: -6.342873
    y: 0.9999979
    z: 2.894829
  rotation:
    x: 0
    y: 0
    z: 0
  scale:
    x: 1
    y: 1
    z: 1
lockers: []
schematics:
- schematic_name: 'DF_Surface'
  culling_type: None
  is_pickable: false
  position:
    x: 0
    y: 1000
    z: 0
  rotation:
    x: 0
    y: 0
    z: 0
  scale:
    x: 1
    y: 1
    z: 1
  room_type: Surface
- schematic_name: 'Checkpoint'
  culling_type: None
  is_pickable: false
  position:
    x: 0
    y: 0
    z: 0
  rotation:
    x: 0
    y: 0
    z: 0
  scale:
    x: 1
    y: 1
    z: 1
  room_type: HczEzCheckpointA
- schematic_name: 'Checkpoint'
  culling_type: None
  is_pickable: false
  position:
    x: 0
    y: 0
    z: 0
  rotation:
    x: 0
    y: 0
    z: 0
  scale:
    x: 1
    y: 1
    z: 1
  room_type: HczEzCheckpointB
- schematic_name: 'biohazard'
  culling_type: None
  is_pickable: false
  position:
    x: 1.147179
    y: 0.9682007
    z: -2.851192
  rotation:
    x: 0
    y: 0
    z: 0
  scale:
    x: 1
    y: 1
    z: 1
  room_type: HczNuke
- schematic_name: 'RadiationHazard'
  culling_type: None
  is_pickable: false
  position:
    x: 1.147179
    y: 1.068176
    z: -2.75119
  rotation:
    x: 0
    y: 0
    z: 0
  scale:
    x: 1
    y: 1
    z: 1
  room_type: HczNuke
- schematic_name: 'VenomCD'
  culling_type: None
  is_pickable: false
  position:
    x: 17.32
    y: 920.8
    z: -50.71
  rotation:
    x: 0
    y: 0
    z: 0
  scale:
    x: 1
    y: 1
    z: 1
  room_type: Surface
- schematic_name: 'Hallway(049)'
  culling_type: None
  is_pickable: false
  position:
    x: -10.91
    y: 0
    z: 0
  rotation:
    x: 0
    y: 90
    z: 0
  scale:
    x: 0.68
    y: 0.75
    z: 7.4
  room_type: LczClassDSpawn
- schematic_name: 'HallwayEnd'
  culling_type: None
  is_pickable: false
  position:
    x: -25.19
    y: 0
    z: 0
  rotation:
    x: 0
    y: 90
    z: 0
  scale:
    x: 0.68
    y: 0.75
    z: 1
  room_type: LczClassDSpawn
- schematic_name: 'OR_914'
  culling_type: None
  is_pickable: false
  position:
    x: 0
    y: 0
    z: 0
  rotation:
    x: 0
    y: 0
    z: 0
  scale:
    x: 1
    y: 1
    z: 1
  room_type: Lcz914
