# Whether the default player spawnpoints should be removed. Keep in mind, that given role spawnpoint will be removed only if there is at least one custom spawn point of that type.
remove_default_spawn_points: false
# List of possible names for ragdolls spawned by RagdollSpawnPoints.
ragdoll_role_names:
  ClassD:
  - 'D-9341'
vanilla_doors: {}
vanilla_tesla_properties:
  ignored_roles: []
  ignored_items: []
  inventory_item: true
  damage_multiplier: 1
doors:
- door_type: HeavyContainmentDoor
  is_open: false
  is_locked: false
  keycard_permissions: ContainmentLevelTwo
  ignored_damage_sources: Weapon
  door_health: 150
  lock_on_event: None
  position:
    x: -5.328484
    y: 0
    z: -1.388123
  rotation:
    x: 0
    y: 0
    z: 0
  scale:
    x: 1
    y: 1
    z: 1
  room_type: Hcz939
- door_type: HeavyContainmentDoor
  is_open: false
  is_locked: false
  keycard_permissions: ContainmentLevelTwo
  ignored_damage_sources: Weapon
  door_health: 150
  lock_on_event: None
  position:
    x: 86.13902
    y: -1011.661
    z: 69.8582
  rotation:
    x: 0
    y: 45
    z: 0
  scale:
    x: 1
    y: 1
    z: 1
  room_type: Surface
- door_type: HeavyContainmentDoor
  is_open: false
  is_locked: false
  keycard_permissions: ContainmentLevelTwo
  ignored_damage_sources: Weapon
  door_health: 150
  lock_on_event: None
  position:
    x: 85.9621
    y: -1011.661
    z: 80.05535
  rotation:
    x: 0
    y: 45
    z: 0
  scale:
    x: 1
    y: 1
    z: 1
  room_type: Surface
- door_type: HeavyContainmentDoor
  is_open: false
  is_locked: false
  keycard_permissions: ContainmentLevelTwo
  ignored_damage_sources: Weapon
  door_health: 150
  lock_on_event: None
  position:
    x: 85.6886
    y: -1000.015
    z: 69.44279
  rotation:
    x: 0
    y: 45
    z: 0
  scale:
    x: 1
    y: 1
    z: 1
  room_type: Surface
- door_type: HeavyContainmentDoor
  is_open: false
  is_locked: false
  keycard_permissions: ContainmentLevelTwo
  ignored_damage_sources: Weapon
  door_health: 150
  lock_on_event: None
  position:
    x: 85.81934
    y: -1000.018
    z: 80.46195
  rotation:
    x: 0
    y: 45
    z: 0
  scale:
    x: 1
    y: 1
    z: 1
  room_type: Surface
- door_type: HeavyContainmentDoor
  is_open: false
  is_locked: false
  keycard_permissions: None
  ignored_damage_sources: Weapon
  door_health: 150
  lock_on_event: None
  position:
    x: -0.1544113
    y: 0
    z: 4.062988
  rotation:
    x: 0
    y: 180
    z: 0
  scale:
    x: 1
    y: 1
    z: 1
  room_type: HczCrossing
work_stations: []
item_spawn_points: []
player_spawn_points: []
ragdoll_spawn_points: []
shooting_targets: []
primitives: []
light_sources: []
room_lights: []
teleports: []
lockers: []
schematics:
- schematic_name: 'DF_Surface'
  culling_type: None
  is_pickable: false
  position:
    x: 0
    y: 1000
    z: 0
  rotation:
    x: 0
    y: 0
    z: 0
  scale:
    x: 1
    y: 1
    z: 1
  room_type: Surface
