# Whether the default player spawnpoints should be removed. Keep in mind, that given role spawnpoint will be removed only if there is at least one custom spawn point of that type.
remove_default_spawn_points: false
# List of possible names for ragdolls spawned by RagdollSpawnPoints.
ragdoll_role_names:
  ClassD:
  - 'D-9341'
vanilla_doors: {}
vanilla_tesla_properties:
  ignored_roles: []
  ignored_items: []
  inventory_item: true
  damage_multiplier: 1
doors:
- door_type: HeavyContainmentDoor
  is_open: false
  is_locked: false
  keycard_permissions: ContainmentLevelTwo
  ignored_damage_sources: Weapon
  door_health: 150
  lock_on_event: None
  position:
    x: -5.328484
    y: 0
    z: -1.388123
  rotation:
    x: 0
    y: 0
    z: 0
  scale:
    x: 1
    y: 1
    z: 1
  room_type: Hcz939
- door_type: LightContainmentDoor
  is_open: false
  is_locked: true
  keycard_permissions: None
  ignored_damage_sources: Weapon
  door_health: 9999
  lock_on_event: None
  position:
    x: -1.5
    y: 0
    z: 2.384186E-07
  rotation:
    x: 0
    y: -270
    z: 0
  scale:
    x: 1
    y: 1
    z: 1
  room_type: LczArmory
work_stations: []
item_spawn_points: []
player_spawn_points: []
ragdoll_spawn_points: []
shooting_targets: []
primitives: []
light_sources:
- color: 'blue'
  intensity: 1
  range: 1
  shadows: false
  position:
    x: -1.620003
    y: 1.369995
    z: -4.099998
  room_type: HczHid
- color: 'blue'
  intensity: 1
  range: 1.10000002
  shadows: false
  position:
    x: -2.100006
    y: 3.03
    z: 2.384186E-07
  room_type: LczArmory
room_lights: []
teleports:
- target_teleporters:
  - id: 0
    chance: 100
  allowed_roles:
  - 'Scp0492'
  - 'Scp049'
  - 'Scp096'
  - 'Scp106'
  - 'Scp173'
  - 'Scp939'
  - 'Scp3114'
  - 'ZombieFlamingo'
  - 'ClassD'
  - 'Scientist'
  - 'FacilityGuard'
  - 'NtfPrivate'
  - 'NtfSergeant'
  - 'NtfSpecialist'
  - 'NtfCaptain'
  - 'ChaosConscript'
  - 'ChaosRifleman'
  - 'ChaosRepressor'
  - 'ChaosMarauder'
  - 'Tutorial'
  - 'AlphaFlamingo'
  - 'Flamingo'
  cooldown: 1
  teleport_flags: Player
  lock_on_event: None
  teleport_sound_id: -1
  player_rotation_x: 120
  player_rotation_y: 90
  room_type: Surface
  object_id: 1
  position:
    x: 35.39892
    y: 951.1983
    z: -22.04308
  rotation:
    x: 0
    y: 0
    z: 0
  scale:
    x: 1
    y: 1
    z: 1
- target_teleporters:
  - id: 1
    chance: 100
  allowed_roles:
  - 'Scp0492'
  - 'Scp049'
  - 'Scp096'
  - 'Scp106'
  - 'Scp173'
  - 'Scp939'
  - 'Scp3114'
  - 'ZombieFlamingo'
  - 'ClassD'
  - 'Scientist'
  - 'FacilityGuard'
  - 'NtfPrivate'
  - 'NtfSergeant'
  - 'NtfSpecialist'
  - 'NtfCaptain'
  - 'ChaosConscript'
  - 'ChaosRifleman'
  - 'ChaosRepressor'
  - 'ChaosMarauder'
  - 'Tutorial'
  - 'AlphaFlamingo'
  - 'Flamingo'
  cooldown: 1
  teleport_flags: Player
  lock_on_event: None
  teleport_sound_id: -1
  player_rotation_x: 90
  player_rotation_y: 90
  room_type: LczClassDSpawn
  object_id: 0
  position:
    x: -24.98083
    y: 1.0375
    z: 0.0004043579
  rotation:
    x: 0
    y: 0
    z: 0
  scale:
    x: 1
    y: 1
    z: 1
- target_teleporters:
  - id: 2
    chance: 100
  allowed_roles:
  - 'Scp0492'
  - 'Scp049'
  - 'Scp096'
  - 'Scp106'
  - 'Scp173'
  - 'Scp939'
  - 'Scp3114'
  - 'ZombieFlamingo'
  - 'ClassD'
  - 'Scientist'
  - 'FacilityGuard'
  - 'NtfPrivate'
  - 'NtfSergeant'
  - 'NtfSpecialist'
  - 'NtfCaptain'
  - 'ChaosConscript'
  - 'ChaosRifleman'
  - 'ChaosRepressor'
  - 'ChaosMarauder'
  - 'Tutorial'
  - 'AlphaFlamingo'
  - 'Flamingo'
  cooldown: 1
  teleport_flags: Player
  lock_on_event: None
  teleport_sound_id: -1
  player_rotation_x: 180
  player_rotation_y: 
  room_type: Surface
  object_id: 3
  position:
    x: 17.23956
    y: 971.282
    z: -16.36187
  rotation:
    x: 0
    y: 0
    z: 0
  scale:
    x: 1
    y: 1
    z: 1
- target_teleporters:
  - id: 3
    chance: 100
  allowed_roles:
  - 'Scp0492'
  - 'Scp049'
  - 'Scp096'
  - 'Scp106'
  - 'Scp173'
  - 'Scp939'
  - 'Scp3114'
  - 'ZombieFlamingo'
  - 'ClassD'
  - 'Scientist'
  - 'FacilityGuard'
  - 'NtfPrivate'
  - 'NtfSergeant'
  - 'NtfSpecialist'
  - 'NtfCaptain'
  - 'ChaosConscript'
  - 'ChaosRifleman'
  - 'ChaosRepressor'
  - 'ChaosMarauder'
  - 'Tutorial'
  - 'AlphaFlamingo'
  - 'Flamingo'
  cooldown: 1
  teleport_flags: Player
  lock_on_event: None
  teleport_sound_id: -1
  player_rotation_x: 270
  player_rotation_y: 180
  room_type: LczArmory
  object_id: 2
  position:
    x: -1.673722
    y: 0.9999995
    z: -0.02741218
  rotation:
    x: 0
    y: 0
    z: 0
  scale:
    x: 1
    y: 1
    z: 1
lockers: []
schematics:
- schematic_name: 'DF_Surface'
  culling_type: None
  is_pickable: false
  position:
    x: 0
    y: 1000
    z: 0
  rotation:
    x: 0
    y: 0
    z: 0
  scale:
    x: 1
    y: 1
    z: 1
  room_type: Surface
- schematic_name: 'Checkpoint'
  culling_type: None
  is_pickable: false
  position:
    x: 0
    y: 0
    z: 0
  rotation:
    x: 0
    y: 0
    z: 0
  scale:
    x: 1
    y: 1
    z: 1
  room_type: HczEzCheckpointA
- schematic_name: 'Checkpoint'
  culling_type: None
  is_pickable: false
  position:
    x: 0
    y: 0
    z: 0
  rotation:
    x: 0
    y: 0
    z: 0
  scale:
    x: 1
    y: 1
    z: 1
  room_type: HczEzCheckpointB
- schematic_name: 'biohazard'
  culling_type: None
  is_pickable: false
  position:
    x: 1.147179
    y: 0.9682007
    z: -2.851192
  rotation:
    x: 0
    y: 0
    z: 0
  scale:
    x: 1
    y: 1
    z: 1
  room_type: HczNuke
- schematic_name: 'RadiationHazard'
  culling_type: None
  is_pickable: false
  position:
    x: 1.147179
    y: 1.068176
    z: -2.75119
  rotation:
    x: 0
    y: 0
    z: 0
  scale:
    x: 1
    y: 1
    z: 1
  room_type: HczNuke
- schematic_name: 'VenomCD'
  culling_type: None
  is_pickable: false
  position:
    x: 17.32
    y: 920.8
    z: -50.71
  rotation:
    x: 0
    y: 0
    z: 0
  scale:
    x: 1
    y: 1
    z: 1
  room_type: Surface
- schematic_name: 'Hallway(049)'
  culling_type: None
  is_pickable: false
  position:
    x: -10.91
    y: 0
    z: 0
  rotation:
    x: 0
    y: 90
    z: 0
  scale:
    x: 0.68
    y: 0.75
    z: 7.4
  room_type: LczClassDSpawn
